import requests
import config
from notifier import notify_phone

import requests
import json
import config
from notifier import notify_phone

ORCHESTRATOR_SYSTEM = """You are a signal detection analyzer for a bridge agent. 
You will be given a message generated by an AI assistant.
Your ONLY job is to output a raw JSON object containing three fields:
1. "is_done": true if the assistant explicitly stated the task is completely finished, otherwise false.
2. "is_error": true ONLY if the message contains an actual python traceback, a compilation crash, or the AI explicitly says it is blocked/crashed and cannot proceed. Do NOT flag as true if the message merely mentions the word "error" (e.g. "error handling" or "error messages").
3. "phase_tag": a brief 2-3 word summary of what phase the message represents (e.g. "Reviewing plan", "Implementing chunk", "Reporting error").

Output ONLY valid JSON. Do not use markdown blocks. Do not add conversational text."""

def analyze_message(text: str, system: str = ORCHESTRATOR_SYSTEM) -> dict:
    """
    POSTs to OLLAMA_URL to analyze the text for DONE or ERROR signals.
    Returns a dictionary with 'is_done', 'is_error', and 'phase_tag'.
    """
    # Truncate text if it's too long to save processing time
    truncated_text = text if len(text) < 4000 else text[:2000] + "\n...[truncated]...\n" + text[-2000:]
    
    payload = {
        "model": config.OLLAMA_MODEL,
        "prompt": f"Analyze this message:\n\n{truncated_text}",
        "system": system,
        "stream": False,
        "format": "json" # Force JSON output if supported by model
    }
    
    default_result = {"is_done": False, "is_error": False, "phase_tag": "Unknown"}
    
    try:
        print(f"[Orchestrator] Analyzing message via {config.OLLAMA_MODEL}...")
        response = requests.post(config.OLLAMA_URL, json=payload, timeout=60)
        response.raise_for_status()
        
        result = response.json()
        raw_output = result.get("response", "").strip()
        
        # Clean up in case model wrapped in markdown
        if raw_output.startswith("```json"):
            raw_output = raw_output[7:]
        if raw_output.endswith("```"):
            raw_output = raw_output[:-3]
            
        parsed = json.loads(raw_output.strip())
        print(f"[Orchestrator] Analysis result: {parsed}")
        
        # Ensure fallback fields
        return {
            "is_done": bool(parsed.get("is_done", False)),
            "is_error": bool(parsed.get("is_error", False)),
            "phase_tag": str(parsed.get("phase_tag", "Unknown"))
        }
        
    except json.JSONDecodeError as e:
        print(f"[Orchestrator] Failed to parse JSON from model: {e}")
        return default_result
    except Exception as e:
        print(f"[Orchestrator] Error calling Ollama: {e}")
        # We don't want to crash the whole bridge if analysis fails, just return defaults
        # But we do want to notify if it's completely down.
        if "Connection" in str(e) or "404" in str(e):
             notify_phone(f"Orchestrator failed to call Ollama: {e}", "Bridge Error")
        return default_result
